# Generated by Django 5.0.4 on 2024-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mainPage/images/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.CharField(choices=[('Front-end', 'Web Service'), ('Mobile', 'Build Applications'), ('Web Scrapping', 'Data Collection'), ('Compute', 'Compute Services'), ('Database', 'Database Services'), ('Networking', 'Networking Services'), ('DevOps', 'Development and DevOps'), ('Migration', 'Migration Services'), ('Managed', 'Managed Services'), ('Support', 'Support and Consulting')], max_length=50),
        ),
    ]
