# Generated by Django 5.0.4 on 2024-08-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_services_image_alter_services_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
